version: "3.7"
services:
  frontend:
    build:
      context: frontend
      args:
        FRONT_END_PORT: ${FRONT_END_PORT}
    ports:
      - ${FRONT_END_PORT}:${FRONT_END_PORT}
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    container_name: frontend
    restart: always
  server:
    container_name: server
    restart: always
    build:
      context: server
      args:
        NODE_PORT: ${NODE_PORT}
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.4
    volumes:
      - ./data_db_log:/data/db
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}

  nginx:
      container_name: nginx
      restart: always
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - frontend
        - server
      command: [ "sh", "-c", "nginx -t && nginx -g 'daemon off;'" ]
